
server:
  port: 8031

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/
  instance:       #  显示ip地址 默认是false
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: microservice-hystrix-turbine

turbine:
  aggregator:
    clusterConfig: MICROSERVICE-COMSUMER-MOVIE-RIBBON
  appConfig:  microservice-comsumer-movie-ribbon-with-Hystrix #要监控的集群


